### ISSUE TITLE
Can we document Effect?

### ISSUE THREAD

**Issue by newlandsvalley** [purescript/purescript-effect#5]
Great work in getting so many libraries updated for 0.12.

The link in Effect.purs to 
```
See [Handling Native Effects with the Effect Monad](http://www.purescript.org/learn/eff/)
```
is broken.  I imagine because no-one's yet had time to do the documentation.  But I think it's quite important to do this quite soon after the release - it's a major change.

**Comment by hdgarrood** [comment]
The article which that URL used to point to is now here: https://github.com/purescript/documentation/blob/master/guides/Eff.md

However most of what’s in there is no longer relevant since we removed the rows.

**Comment by newlandsvalley** [comment]
Yes - I think this could be confusing for new users.  And for me, I'm still not entirely clear about the impact of this change - particularly on Aff and in general how native effects are now to be handled.

**Comment by hdgarrood** [comment]
For both `Aff` and `Effect`, we're just no longer tracking effects in the type, so you don't need to bother with all those row type variables and getting rows to line up any more. It's really not that significant a change, it doesn't really represent a shift in how native effects are handled in general; the answer to your question really is basically just "the same as before".

**Comment by newlandsvalley** [comment]
Ah - good news!  So, no JavaScript changes needed at all if I'm wrapping a web platform API?

**Comment by hdgarrood** [comment]
Correct

**Comment by Elvecent** [comment]
Beginner here: that was indeed confusing. I was following the mentioned guide on using Eff and got a weird error when I tried installing relevant packages. The error said about duplicate definition of Data.Monoid, since `purescript-eff` has a dependency on `purescript-monoid` which turned out to be deprecated since Data.Monoid is now in Prelude. It took reading several github pages and some twitter to even understand what's going on. And I am still not sure what's the canonical way to do IO (if it exists at all). Do I use `purescript-effect` or `purescript-io` or `purescript-run`? Does it even matter? Which of those are commonly used in popular libraries?

**Comment by piton182** [comment]
Where can I read about "removing rows"? No more row polymorphism?

**Comment by JordanMartinez** [comment]
@piton182 Justin has a good summary to various links:
https://purescript-resources.readthedocs.io/en/latest/eff-to-effect.html
